-- ============================================================================
-- V8: Add IBAN column to accounts
-- Adds ISO 13616 IBAN as a human-friendly account identifier (banking UX best
-- practice). UUID remains the canonical primary key.
-- For existing rows (demo/dev environments), backfill with a deterministic
-- placeholder derived from the UUID so the NOT NULL + UNIQUE constraints can
-- be enforced. Real IBANs (with valid mod-97 check digits) are regenerated by
-- the application layer on next account touch.
-- ============================================================================

ALTER TABLE accounts ADD COLUMN iban VARCHAR(34);

-- Deterministic backfill: DE00 + demo BLZ + 10 digits from UUID.
-- Check digits '00' are intentionally invalid — filtered out by the app-side
-- validator so these legacy rows cannot be used as transfer targets until
-- regenerated.
UPDATE accounts
SET iban = 'DE00' || '50010517'
           || LPAD(
               (ABS(('x' || SUBSTR(REPLACE(id::text, '-', ''), 1, 15))::bit(60)::bigint) % 10000000000)::text,
               10, '0')
WHERE iban IS NULL;

ALTER TABLE accounts ALTER COLUMN iban SET NOT NULL;
ALTER TABLE accounts ADD CONSTRAINT uq_accounts_iban UNIQUE (iban);
CREATE INDEX idx_accounts_iban ON accounts(iban);
