package com.mariosmant.fintech.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.boot.info.BuildProperties;
import org.springframework.boot.info.GitProperties;
import org.springframework.context.ApplicationListener;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Component;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Arrays;

/**
 * Emits a structured, human-readable banner once the application has fully
 * started ({@link ApplicationReadyEvent}), summarising build / git / runtime
 * metadata in a single log line block.
 *
 * <p>Purpose: operability. On every deploy and every pod restart the
 * first log entry tells a responder <em>exactly</em> which commit, branch,
 * Java version and profile is running — without having to hit
 * {@code /actuator/info}. This aligns with SRE/observability practice of
 * making provenance trivially auditable from log retention alone.</p>
 *
 * <p>{@link BuildProperties} and {@link GitProperties} are autowired
 * {@code @Autowired(required=false)} because {@code build-info.properties}
 * and {@code git.properties} are only generated by the Maven build
 * (see {@code poc-fintech-boot/pom.xml}); they are absent when the app is
 * started from the IDE without a prior {@code mvn package}, and in that case
 * the listener still runs with sensible fallbacks.</p>
 *
 * @author mariosmant
 * @since 1.0.0
 */
@Component
public class StartupBannerListener implements ApplicationListener<ApplicationReadyEvent> {

    private static final Logger log = LoggerFactory.getLogger(StartupBannerListener.class);

    private final Environment environment;
    private final BuildProperties buildProperties;
    private final GitProperties gitProperties;

    /**
     * @param environment     the Spring {@link Environment} (active profiles, port)
     * @param buildProperties build metadata from {@code META-INF/build-info.properties};
     *                        {@code null} when running without {@code mvn package}
     * @param gitProperties   git metadata from {@code git.properties};
     *                        {@code null} outside a Git checkout or for source-zip builds
     */
    public StartupBannerListener(Environment environment,
                                 @Autowired(required = false) BuildProperties buildProperties,
                                 @Autowired(required = false) GitProperties gitProperties) {
        this.environment = environment;
        this.buildProperties = buildProperties;
        this.gitProperties = gitProperties;
    }

    @Override
    public void onApplicationEvent(ApplicationReadyEvent event) {
        log.info("\n{}", renderBanner());
    }

    /**
     * Builds the banner string. Package-private for unit testing — lets the test
     * assert content without capturing the SLF4J appender.
     */
    String renderBanner() {
        String appName = value("spring.application.name", "poc-fintech");
        String version = buildProperties != null ? buildProperties.getVersion() : "unknown";
        String buildTime = buildProperties != null && buildProperties.getTime() != null
                ? buildProperties.getTime().toString()
                : "unknown";
        String commit = gitProperties != null ? gitProperties.getShortCommitId() : "unknown";
        String branch = gitProperties != null ? gitProperties.getBranch() : "unknown";
        String dirty = gitProperties != null ? gitProperties.get("dirty") : null;
        String profiles = Arrays.toString(environment.getActiveProfiles());
        if ("[]".equals(profiles)) {
            profiles = "[default]";
        }
        String port = value("server.port", "8080");
        String host;
        try {
            host = InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            host = "unknown";
        }
        String javaVersion = System.getProperty("java.version", "unknown");
        String javaVendor = System.getProperty("java.vendor", "unknown");

        return """
                ════════════════════════════════════════════════════════════════════
                 %s %s  is READY
                ────────────────────────────────────────────────────────────────────
                   Build time : %s
                   Git commit : %s%s (branch %s)
                   Profiles   : %s
                   Host:Port  : %s:%s
                   Java       : %s (%s)
                ════════════════════════════════════════════════════════════════════
                """.formatted(
                        appName,
                        version,
                        buildTime,
                        commit,
                        "true".equalsIgnoreCase(dirty) ? " (DIRTY)" : "",
                        branch,
                        profiles,
                        host,
                        port,
                        javaVersion,
                        javaVendor);
    }

    private String value(String key, String fallback) {
        String v = environment.getProperty(key);
        return (v == null || v.isBlank()) ? fallback : v;
    }
}

